# Generated by Django 3.0.4 on 2020-03-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_auto_20200315_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='title',
        ),
    ]
