# Generated by Django 3.0.4 on 2020-03-15 13:53

from django.db import migrations, models
import my_site.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_auto_20200315_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('resume', models.FileField(null=True, upload_to='documents/%Y/%m/%d/', validators=[my_site.validators.validate_file_size])),
            ],
        ),
    ]
